name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4      # Node first
        with:
          node-version: 20
          cache: 'pnpm'

      - uses: pnpm/action-setup@v3       # then pnpm
        with:
          version: 10

      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm exec tsc --noEmit
