name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm exec tsc --noEmit
